// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: internal/proto/scrape.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company string `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
}

func (x *TryRequest) Reset() {
	*x = TryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_scrape_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryRequest) ProtoMessage() {}

func (x *TryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_scrape_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryRequest.ProtoReflect.Descriptor instead.
func (*TryRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_scrape_proto_rawDescGZIP(), []int{0}
}

func (x *TryRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

type TryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site  string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TryReply) Reset() {
	*x = TryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_scrape_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TryReply) ProtoMessage() {}

func (x *TryReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_scrape_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TryReply.ProtoReflect.Descriptor instead.
func (*TryReply) Descriptor() ([]byte, []int) {
	return file_internal_proto_scrape_proto_rawDescGZIP(), []int{1}
}

func (x *TryReply) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *TryReply) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_internal_proto_scrape_proto protoreflect.FileDescriptor

var file_internal_proto_scrape_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a,
	0x0a, 0x54, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x22, 0x34, 0x0a, 0x08, 0x54, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x2a, 0x0a, 0x07, 0x53,
	0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x03, 0x54, 0x72, 0x79, 0x12, 0x0b, 0x2e,
	0x54, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x54, 0x72, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_scrape_proto_rawDescOnce sync.Once
	file_internal_proto_scrape_proto_rawDescData = file_internal_proto_scrape_proto_rawDesc
)

func file_internal_proto_scrape_proto_rawDescGZIP() []byte {
	file_internal_proto_scrape_proto_rawDescOnce.Do(func() {
		file_internal_proto_scrape_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_scrape_proto_rawDescData)
	})
	return file_internal_proto_scrape_proto_rawDescData
}

var file_internal_proto_scrape_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_scrape_proto_goTypes = []interface{}{
	(*TryRequest)(nil), // 0: TryRequest
	(*TryReply)(nil),   // 1: TryReply
}
var file_internal_proto_scrape_proto_depIdxs = []int32{
	0, // 0: Scraper.Try:input_type -> TryRequest
	1, // 1: Scraper.Try:output_type -> TryReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_scrape_proto_init() }
func file_internal_proto_scrape_proto_init() {
	if File_internal_proto_scrape_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_scrape_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_scrape_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_scrape_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_scrape_proto_goTypes,
		DependencyIndexes: file_internal_proto_scrape_proto_depIdxs,
		MessageInfos:      file_internal_proto_scrape_proto_msgTypes,
	}.Build()
	File_internal_proto_scrape_proto = out.File
	file_internal_proto_scrape_proto_rawDesc = nil
	file_internal_proto_scrape_proto_goTypes = nil
	file_internal_proto_scrape_proto_depIdxs = nil
}
